### ISSUE TITLE
Enquiring about how to download vgg_conv.pth

### ISSUE THREAD

**Issue by angliunimelb** [SunnerLi/P-Conv#1]
Hi Sunner,

I found that the url for vgg_conv.pth in your code cannot be accessed. Would you mind share your copy of vgg_conv.pth through google drive? Thanks a lot!

**Comment by SunnerLi** [comment]
Hi @angliunimelb ,
sorry to reply you for too late.
In the program, the `vgg_conv.pth` can download automatically.
I had tested the program just a moment ago and it can work.
However, if you want to download the file directly,
Here is the link you want!
```
https://drive.google.com/file/d/1JNrSVZrK4TfC7pFG-r7AOmGvBXF2VFOt/view?usp=sharing
```
But I recommend you to let the program download the file automatically.
If there is any problem, it is pleased to tell me :-)
