### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by NerminSalem** [SunnerLi/P-Conv#2]
thanks alot for sharing yr code, i m trying to make a training with my own dataset but i m getting this error can u help?
thanks
![screenshot from 2018-11-13 11-27-10](https://user-images.githubusercontent.com/26221951/48403772-4c0df200-e737-11e8-965d-73c16ecf16ff.png)

**Comment by NerminSalem** [comment]
i have also downloaded the model u provided but the result is soo bad 
how many epoches do i have to make in order to get good results?

**Comment by SunnerLi** [comment]
Hi @NerminSalem ,
In my experiment, I spend about 2~4 weeks to train toward Place365 with single GTX 1080-ti.
However, the performance cannot act like the performance that the paper mentioned.
Moreover, the model converges slow during training.
I also demonstrate with the image which I capture by myself.
Nevertheless, the render performance is bad.
You can check in the readme.



To sum up for the answer,
I think you can try for more training epoch.
Also, the diversity of dataset is also important.
But I think it's hard to re-produce the perfect result which paper mentioned. 
Hope these suggestion can help you.
